name: Create Release and Build EXE

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-exe:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed --icon=icon128.ico --name JellyfinDownloader JellyfinDownloader.py

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/JellyfinDownloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}